const catApi = `[
  {
    "length": "12 to 16 inches",
    "origin": "Southeast Asia",
    "image_link": "https://api-ninjas.com/images/cats/abyssinian.jpg",
    "family_friendly": "3",
    "shedding": "3",
    "general_health": "2",
    "playfulness": "5",
    "children_friendly": "5",
    "grooming": "3",
    "intelligence": "5",
    "other_pets_friendly": "5",
    "min_weight": "6",
    "max_weight": "10",
    "min_life_expectancy": "9",
    "max_life_expectancy": "15",
    "name": "Abyssinian"
  },
  {
    "length": "17 to 25 inches",
    "origin": "Russia",
    "image_link": "https://api-ninjas.com/images/cats/siberian.jpg",
    "family_friendly": "5",
    "shedding": "4",
    "general_health": "4",
    "playfulness": "5",
    "meowing": "2",
    "children_friendly": "5",
    "stranger_friendly": "4",
    "grooming": "2",
    "intelligence": "4",
    "other_pets_friendly": "4",
    "min_weight": "8",
    "max_weight": "17",
    "min_life_expectancy": "11",
    "max_life_expectancy": "18",
    "name": "Siberian"
  },
  {
    "length": "10 to 12 inches",
    "origin": "Tayside, Scotland",
    "image_link": "https://api-ninjas.com/images/cats/scottish_fold.jpg",
    "family_friendly": "5",
    "shedding": "3",
    "general_health": "3",
    "playfulness": "3",
    "meowing": "4",
    "children_friendly": "5",
    "stranger_friendly": "3",
    "grooming": "2",
    "intelligence": "4",
    "other_pets_friendly": "4",
    "min_weight": "6",
    "max_weight": "13",
    "min_life_expectancy": "11",
    "max_life_expectancy": "14",
    "name": "Scottish Fold"
  },
  {
    "length": "22 to 25 inches, not including tail",
    "origin": "Great Britain",
    "image_link": "https://api-ninjas.com/images/cats/british_shorthair.jpg",
    "family_friendly": "3",
    "shedding": "3",
    "general_health": "4",
    "playfulness": "2",
    "meowing": "4",
    "children_friendly": "4",
    "stranger_friendly": "4",
    "grooming": "4",
    "intelligence": "3",
    "other_pets_friendly": "5",
    "min_weight": "7",
    "max_weight": "17",
    "min_life_expectancy": "12",
    "max_life_expectancy": "17",
    "name": "British Shorthair"
  }
  
]`
